DqdBaiDanhGiaGiuaKy/Models/DqdProduct.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DqdBaiDanhGiaGiuaKy.Models
{
    public class DqdProduct
    {
        [DisplayName(" DQD- Tieu De")]
        [Required(ErrorMessage = "DQD- Hay Nhap Tieu De")]
        public int Id { get; set; }

       

        [DisplayName(" DQD- Tên")]
        [Required(ErrorMessage = " DQD- Vui lòng nhập tên")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Tên phải dài từ 5 đến 100 ký tự")]
        [RegularExpression(@"^[A-ZÀÁÂẨÃÈÉÊẾËÌÍĨỊÒÓÔÕÖÙÚŨỤƯỲÝỶỸ\s]+$", ErrorMessage = "Tên chỉ chứa ký tự viết hoa và khoảng trắng")]
        public string Name { get; set; }

        

        [DisplayName(" DQD- Ảnh")]
        [Required(ErrorMessage = "DQD- Hãy Nhập ẢNh")]
        public string Image { get; set; }

        

        [DisplayName(" DQD- Số")]
        [Required(ErrorMessage = " DQD- Vui lòng nhập số")]
        [Range(1, 100, ErrorMessage = "Số phải nằm trong khoảng từ 1 đến 100")]
        public int Quantity { get; set; }

        

        [DisplayName(" DQD- Số")]
        [Required(ErrorMessage = "Vui lòng nhập số")]
        public int Price { get; set; }

        
        [DisplayName(" DQD- Hoat Dong")]
        [Required(ErrorMessage = " DQD- Vui lòng Nhap Hoat Dong")]
        public string isActive { get; set; }

    }
}

DqdBaiDanhGiaGiuaKy/Controllers/DqdProductController.cs
using System;
using DqdBaiDanhGiaGiuaKy.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DqdBaiDanhGiaGiuaKy.Controllers
{
    public class DqdProductController : Controller
    {
        private static List<DqdProduct> dqdProduct = new List<DqdProduct>()
        {
            new DqdProduct{Id=100, Name="DangQuangDung", Image="K22Cntt1", Quantity=19, Price=2004, isActive="Active"},
            new DqdProduct{Id=101, Name="NguyenKhanhPhuong",Image="K72Cntt1", Quantity=18, Price=2005, isActive="NonActive"}

        };
        // GET: DqdProduct
        public ActionResult Index()
        {
            return View(dqdProduct);
        }

        public ActionResult DqdCreate()
        {
            var dqdProduct = new DqdProduct();
            return View();
        }
        [HttpPost]
        public ActionResult DqdCreate(DqdProduct dqdProduct)
        {
            if (!ModelState.IsValid)
            {
                return View(dqdProduct);
            }
            dqdProduct.Add(dqdProduct);
            return RedirectToAction("Index");
        }
    }
}

DqdBaiDanhGiaGiuaKy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DqdBaiDanhGiaGiuaKy.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DqdBaiDanhGiaGiuaKy/Views/DqdProduct/DqdCreate.cshtml
@model DqdBaiDanhGiaGiuaKy.Models.DqdProduct

@{
    ViewBag.Title = "DqdCreate";
}

<h2>Dqd: Create New</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearRelease, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearRelease, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearRelease, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DqdBaiDanhGiaGiuaKy/Views/DqdProduct/Index.cshtml
@model IEnumerable<DqdBaiDanhGiaGiuaKy.Models.DqdProduct>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isActive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

DqdBaiDanhGiaGiuaKy/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DqdBaiDanhGiaGiuaKy/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DqdBaiDanhGiaGiuaKy/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

DqdBaiDanhGiaGiuaKy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DangQuangDung </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" Dang Quang Dung", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Dqd Product", "Index", "DqdProduct")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>